import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
from PIL import Image
import os
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================
# 1. Data Augmentation

"""
In this part, we use concepts of data augmentations such as horizontal flip, cropping.
We will be using the dataset CIFAR10, which is divide into 80/10/10 for train/validation/test set.
We also normalize it using the average and std deviation of CIFAR10 for faster training.

"""


transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize(
        (0.4914,0.4822,0.4465),
        (0.2023,0.1994,0.2010))])

dataset = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform)

total = len(dataset)
train_size = int(0.8*total)
val_size = int(0.1*total)
test_size = total - train_size - val_size

train_dataset, val_dataset, test_dataset = random_split(
    dataset,[train_size,val_size,test_size])

trainloader = DataLoader(train_dataset,batch_size=128,shuffle=True)
valloader = DataLoader(val_dataset,batch_size=128)
testloader = DataLoader(test_dataset,batch_size=128)

# ===========================================



# ===========================================
# 2. Sobel Edge Filters

"""
In this part, we will define the sobel edge filters, which will be used for edge detection. 
Define for both horizontal and vertical edges. 1 input, 1 output channel and 3x3 kernel.
"""

sobel_x = torch.tensor([
[-1,0,1],
[-2,0,2],
[-1,0,1]],dtype=torch.float32).view(1,1,3,3).to(device)

sobel_y = torch.tensor([
[-1,-2,-1],
[0,0,0],
[1,2,1]],dtype=torch.float32).view(1,1,3,3).to(device)

# ==========================================



# ==========================================
# 3. Texture CNN

"""
In this part, we will be defining the texture CNN, which will learn the texture of an image. 
This CNN inputs the RGB channels, also including batch normalization.
First layer: Input=3, Output=64, Kernel=3x3
Second layer: Input=64, Output=128, Kernel=3x3
Third layer: Input=128, Output=256, Kernel=3x3
"""

texture_conv1 = nn.Conv2d(3,64,3,padding=1).to(device)
texture_bn1 = nn.BatchNorm2d(64).to(device)

texture_conv2 = nn.Conv2d(64,128,3,padding=1).to(device)
texture_bn2 = nn.BatchNorm2d(128).to(device)

texture_conv3 = nn.Conv2d(128,256,3,padding=1).to(device)
texture_bn3 = nn.BatchNorm2d(256).to(device)

# ================================================



# ================================================
# 4. Shape CNN

"""
In this part, we will be defining the shape CNN, which will learn the shape of an image using edges. 
This CNN inputs the edge channel, which we generated by passing the input through the sobel's filters.
irst layer: Input=1, Output=64, Kernel=3x3
Second layer: Input=64, Output=128, Kernel=3x3
Third layer: Input=128, Output=256, Kernel=3x3
"""

shape_conv1 = nn.Conv2d(1,64,3,padding=1).to(device)
shape_bn1 = nn.BatchNorm2d(64).to(device)

shape_conv2 = nn.Conv2d(64,128,3,padding=1).to(device)
shape_bn2 = nn.BatchNorm2d(128).to(device)

shape_conv3 = nn.Conv2d(128,256,3,padding=1).to(device)
shape_bn3 = nn.BatchNorm2d(256).to(device)

# =================================================



# =================================================
# 5. U-Net Style Decoder

"""
In this part, we define a U-Net style decoder. It will used to visualize, 
and see if the NN has learnt. The second layer is unique, since it inputs dec1 and s1,
which is a skip connection and will bring back fine details lost during max pooling.
Inputs 8x8 feature maps
First layer: Input=128, Output=64, Kernel=3x3
Second layer: Input=64+64, Output=32, Kernel=3x3  
Third layer: Input=32, Output=1, Kernel=3x3
"""

dec1 = nn.Conv2d(128,64,3,padding=1).to(device)
dec2 = nn.Conv2d(128,32,3,padding=1).to(device)
dec3 = nn.Conv2d(32,1,3,padding=1).to(device)

# =================================================



# =================================================
# 6. Fully Connected Layers

"""
In thsi part, we combine the learning from the texture and shape CNN. 
We combine the texture output, which is 256x4x4, with shape output, which is also 256x4x4.
Introduced dropout to reduce overfitting
"""

fc1 = nn.Linear(256*4*4*2,1024).to(device)
dropout = nn.Dropout(0.5).to(device)
fc2 = nn.Linear(1024,10).to(device)

# =================================================



# =================================================
# 7. Parameters

"""
In this part, I will defining the parameters. I will be using Adam optiimizer.
I will be using StepLR. Since I am not using classes, I manually define all the parameters.
I will be using L1 loss for edges.
"""

params = list(texture_conv1.parameters()) + \
list(texture_bn1.parameters()) + \
list(texture_conv2.parameters()) + \
list(texture_bn2.parameters()) + \
list(texture_conv3.parameters()) + \
list(texture_bn3.parameters()) + \
list(shape_conv1.parameters()) + \
list(shape_bn1.parameters()) + \
list(shape_conv2.parameters()) + \
list(shape_bn2.parameters()) + \
list(shape_conv3.parameters()) + \
list(shape_bn3.parameters()) + \
list(dec1.parameters()) + \
list(dec2.parameters()) + \
list(dec3.parameters()) + \
list(fc1.parameters()) + \
list(fc2.parameters())

optimizer = torch.optim.Adam(params,lr=0.001)

scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer,
    step_size=20,
    gamma=0.5)

classification_loss = nn.CrossEntropyLoss()
edge_loss = nn.L1Loss()

# =============================================



# =============================================
# 8. Forward Propagation

"""
In this part, we define forward propagation. First we grayscale the image and apply sobel's filters.
Then we define forward propagation for texture and shape CNN. We also define the decoder.
For this, we input the 8x8 compressed features, which we scale to 16x16.
Following this, we concatenate this with s1 to restore details.  
"""

def forward(x):

    gray = torch.mean(x,dim=1,keepdim=True)

    edge_x = F.conv2d(gray,sobel_x,padding=1)
    edge_y = F.conv2d(gray,sobel_y,padding=1)
    edges = torch.sqrt(edge_x**2 + edge_y**2)

    # Texture
    t1 = F.relu(texture_bn1(texture_conv1(x)))
    t1 = F.max_pool2d(t1,2)
    t2 = F.relu(texture_bn2(texture_conv2(t1)))
    t2 = F.max_pool2d(t2,2)
    t3 = F.relu(texture_bn3(texture_conv3(t2)))
    t3 = F.max_pool2d(t3,2)

    # Shape
    s1 = F.relu(shape_bn1(shape_conv1(edges)))
    s1 = F.max_pool2d(s1,2)
    s2 = F.relu(shape_bn2(shape_conv2(s1)))
    s_mid = F.max_pool2d(s2,2)   # used by decoder for reconstruction
    s3 = F.relu(shape_bn3(shape_conv3(s_mid)))
    s3 = F.max_pool2d(s3,2)

    # Decoder
    d = F.relu(dec1(s_mid))
    d = F.interpolate(d,scale_factor=2,mode="bilinear")
    d = torch.cat((d,s1),dim=1)
    d = F.relu(dec2(d))
    reconstructed_edges = dec3(d)

    reconstructed_edges = F.interpolate(
        reconstructed_edges,
        size=(32,32),
        mode="bilinear",
        align_corners=False)

    t = t3.view(t3.size(0),-1)
    s = s3.view(s3.size(0),-1)
    combined = torch.cat((t,0.5*s),dim=1)

    out = F.relu(fc1(combined))
    out = dropout(out)
    out = fc2(out)

    return out,edges,reconstructed_edges

# ================================================



# ================================================
# 9. Accuracy

"""
In this part, we find the accuracy of our model using the defined function.
"""

def evaluate(loader):

    correct = 0
    total = 0

    with torch.no_grad():

        for images,labels in loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs,_,_ = forward(images)

            preds = torch.argmax(outputs,dim=1)

            total += labels.size(0)
            correct += (preds==labels).sum().item()

    return 100*correct/total

# ===============================================



# ===============================================
# 10. Training

"""
In this part, I will be defining the training loop. I defined loss1 and loss2.
Total loss is defined as loss1 + 0.7*loss2. 
"""

epochs = 50

for epoch in range(epochs):

    for images,labels in trainloader:

        images = images.to(device)
        labels = labels.to(device)

        outputs,true_edges,pred_edges = forward(images)

        loss1 = classification_loss(outputs,labels)
        loss2 = edge_loss(pred_edges,true_edges)
        loss = loss1 + 0.7*loss2

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    scheduler.step()
    val_acc = evaluate(valloader)
    print("Epoch:",epoch+1,"Validation Accuracy:",val_acc)

# ================================================
# 11. Test accuracy and Edge Visualization

"""
In this part, we see out test accuracy. We also pick the first batch of test images.
We use this for edge reconstruction. 
"""

print("Test Accuracy:",evaluate(testloader))

images,_ = next(iter(testloader))
images = images[:1].to(device)

_,true_edges,pred_edges = forward(images)

true_edges = true_edges[0][0].detach().cpu()
pred_edges = pred_edges[0][0].detach().cpu()

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.title("True edges")
plt.imshow(true_edges,cmap="gray")
plt.subplot(1,2,2)
plt.title("Predicted edges")
plt.imshow(pred_edges,cmap="gray")
plt.show()

# ================================================
# 12. Prediction

"""
In this part, we will see if our idea worked. I have generated a pictures of a cats, 
dogs and frogs with different textures using ChatGPT and Gemini. 
"""

classes = ['airplane','car','bird','cat','deer',
'dog','frog','horse','ship','truck']

def predict_image(path):

    if not os.path.exists(path):
        print("Image not found:",path)
        return

    img = Image.open(path).convert("RGB")

    transform_test = transforms.Compose([
        transforms.Resize((32,32)),
        transforms.ToTensor(),
        transforms.Normalize(
            (0.4914,0.4822,0.4465),
            (0.2023,0.1994,0.2010))])

    img = transform_test(img).unsqueeze(0).to(device)

    with torch.no_grad():

        output,_,_ = forward(img)
        pred = torch.argmax(output,dim=1).item()

    print("Prediction:",classes[pred])


predict_image("test_cat.png")
predict_image("test_dog.png")
predict_image("test_frog.png")
